# -*- coding: utf-8 -*-
"""binomial_options

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RBx5QWVz45zwO2d-RK7aGfJhylF5dZk
"""

import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

def binomial_price_american(S0, K, T, r, sigma, N, option_type="call"):
    dtau = T / N
    u = np.exp(sigma * np.sqrt(dtau))
    d = 1 / u

    p = (np.exp(r * dtau) - d) / (u - d)
    if p <= 0 or p >= 1:
        return np.nan

    discount = np.exp(-r * dtau)

    # compute terminal stock prices
    j = np.arange(N, -1, -1)
    ST = S0 * (u**j) * (d**(N - j))

    # compute terminal option prices
    if option_type == "call":
        option_values = np.maximum(ST - K, 0.0)
    else:
        option_values = np.maximum(K - ST, 0.0)

    # backward induction
    for step in range(N-1, -1, -1):
        # continuation
        option_values = discount * (p * option_values[1:] +
                                    (1 - p) * option_values[:-1])

        ST = S0 * (u**np.arange(step, -1, -1)) * (d**(step - np.arange(step, -1, -1)))

        if option_type == "call":
            exercise = np.maximum(ST - K, 0.0)
        else:
            exercise = np.maximum(K - ST, 0.0)

        option_values = np.maximum(option_values, exercise)

    return option_values[0]

# get data

ticker = "AAPL"
stock = yf.Ticker(ticker)
exp_date = stock.options[0]
chain = stock.option_chain(exp_date)
calls = chain.calls

# current price
S0 = stock.history(period="1d")["Close"].iloc[-1]

# risk free rate
r = 0.037

# exp time
today = dt.datetime.now().date()
expiry_date = dt.datetime.strptime(exp_date, "%Y-%m-%d").date()
T = (expiry_date - today).days / 365

option_type = "call"
N = 1000

strikes = []
market_px = []
binom_px = []

for idx, row in calls.iterrows():
    K = row["strike"]
    market = row["lastPrice"]
    sigma = row["impliedVolatility"]

    if np.isnan(market) or market <= 0:
        continue
    if np.isnan(sigma) or sigma <= 0:
        continue

    # compute binomial price
    model_price = binomial_price(S0, K, T, r, sigma, N, option_type)

    strikes.append(K)
    market_px.append(market)
    binom_px.append(model_price)

# sort
strikes, market_px, binom_px = zip(*sorted(zip(strikes, market_px, binom_px)))

# plot price comparison
plt.figure(figsize=(12, 7))
plt.plot(strikes, market_px, 'ro-', label="Market", linewidth=2)
plt.plot(strikes, binom_px, 'd--', label=f"Binomial (N={N})", linewidth=2, alpha=0.7)
plt.xlabel("Strike Price")
plt.ylabel("Option Price")
plt.title(f"AAPL Call Options: Binomial vs Market ({exp_date})")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# plot absolute error
market_px = np.array(market_px)
binom_px = np.array(binom_px)

plt.figure(figsize=(12, 6))
plt.plot(strikes, np.abs(binom_px - market_px), 'd--', linewidth=2)
plt.xlabel("Strike Price")
plt.ylabel("Absolute Error")
plt.title("Binomial Model Pricing Error")
plt.grid(True)
plt.tight_layout()
plt.show()